FROM golang:1.25.1 AS builder

WORKDIR /build

COPY go.mod  .
COPY go.sum  .
COPY vendor  ./vendor

RUN go mod verify

COPY cmd     ./cmd
COPY service ./service

RUN go build -mod=vendor -o webapi ./cmd/webapi

# ------------------------------------------- #

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /build/webapi .

EXPOSE 3000

VOLUME ["/app/db", "/app/uploads/images"]

CMD ["./webapi"]
