FROM node:20.19.5 AS builder

WORKDIR /app/webui

COPY webui/package.json .
COPY webui/yarn.lock    .
COPY webui/.yarnrc.yml  .
COPY webui/.yarn        ./.yarn

RUN yarn install

COPY webui/index.html     .
COPY webui/vite.config.js .
COPY webui/src            ./src
COPY webui/public         ./public

RUN yarn build

# ----------------------------------------- #

FROM nginx:stable

COPY --from=builder /app/webui/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
